language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
env:
  - DJANGO=Django==1.2.7
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1
  - DJANGO="https://www.djangoproject.com/download/1.6a1/tarball/"
  - DJANGO="-e git+git://github.com/django/django.git#egg=Django"

install:
  - sudo apt-get install libevent-dev
  - pip install $DJANGO --use-mirrors
  - make bootstrap
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} == '2' ]]; then pip install gevent --use-mirrors; fi"
  - "if [[ ${TRAVIS_PYTHON_VERSION} == '3.2' ]]; then pip install -I https://github.com/celery/celery/archive/3.0.zip; fi"
  - "if [[ ${TRAVIS_PYTHON_VERSION::1} == '3' ]]; then pip uninstall django-celery -y; fi"
script:
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven --cov-report term-missing
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.2.7
    - python: "3.2"
      env: DJANGO=Django==1.3.7
    - python: "3.2"
      env: DJANGO=Django==1.4.5
    - python: "3.3"
      env: DJANGO=Django==1.2.7
    - python: "3.3"
      env: DJANGO=Django==1.3.7
    - python: "3.3"
      env: DJANGO=Django==1.4.5
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
after_success:
  - coveralls